import httpx
import asyncio

API_BASE = "http://127.0.0.1:8000"
EMAIL = "admin@admin.com"
PASSWORD = "admin"

DATA_STRUCTURE = {
    "Engineering": {
        "Software Arch": {
            "Microservices vs Monoliths": "Microservices and monoliths are two foundational architectural styles in software engineering. A monolith binds all functionalities into a single codebase and deployment unit. It is easy to develop initially but becomes difficult to scale and deploy as the application grows. Microservices, on the other hand, separate functionalities into independently deployable services that communicate via APIs. While they offer extreme scalability and flexibility, they introduce massive operational complexity, requiring robust CI/CD pipelines, service meshes, and distributed tracing. Choosing between them depends entirely on the team size and business domain complexity.",
            "Event-Driven Architecture": "Event-driven architecture (EDA) revolves around the production, detection, consumption of, and reaction to events. An event is any significant change in state, such as a user purchasing an item. In EDA, services are highly decoupled. Producers emit events without knowing who will consume them, and consumers listen for events without knowing who produced them. Technologies like Apache Kafka or RabbitMQ are typically used as event brokers to ensure reliable delivery. This pattern is essential for building highly responsive, real-time data streaming applications and fits perfectly with serverless computing."
        },
        "AI & Machine Learning": {
            "Transformers Explained": "The Transformer architecture, introduced in the paper 'Attention Is All You Need', revolutionized natural language processing. Unlike RNNs or LSTMs that process data sequentially, transformers process entire sequences simultaneously, allowing for massive parallelization. The core mechanism is 'Self-Attention', which allows the model to weigh the importance of different words in a sentence relative to one another, regardless of their position. This architecture forms the foundation of modern large language models like GPT-4, BERT, and Claude, enabling them to understand context and generate human-like text with unprecedented accuracy.",
            "Vector Embeddings": "Vector embeddings are numerical representations of data (text, images, audio) in high-dimensional space. The key concept is that similar concepts are mapped mathematically close to each other. For example, the vectors for 'king' and 'queen' will be closer together than 'king' and 'apple'. These embeddings are generated by neural networks like sentence-transformers or OpenAI's text-embedding models. When stored in a vector database like pgvector, we can perform extremely fast similarity searches using mathematical operations like Cosine Similarity or Euclidean Distance. This is the exact technology powering our semantic search feature right now!"
        }
    },
    "Personal": {
        "Finances": {
            "2026 Budget Plan": "The financial plan for 2026 involves aggressively optimizing savings while expanding investment portfolios. Key targets include reducing discretionary spending by 15%, maxing out retirement contributions by Q3, and starting a diversified ETF portfolio focusing on emerging markets. Additionally, an emergency fund covering 6 months of expenses must be maintained in a high-yield savings account. Monthly reviews of cash flow will ensure we stay on track to purchase a new piece of real estate by 2028."
        },
        "Travel": {
            "Japan Itinerary": "A comprehensive 14-day trip to Japan. Day 1-4: Tokyo (Shinjuku, Shibuya crossing, Akihabara tech district, and Senso-ji temple). Day 5-7: Kyoto (Fushimi Inari shrine, bamboo forest, and traditional tea ceremony). Day 8-10: Osaka (Dotonbori food street and Universal Studios). Day 11-12: Hiroshima & Miyajima island. Day 13-14: Return to Tokyo for final souvenir shopping. Must buy JR Pass before arriving, and secure portable Wi-Fi at Narita airport. Pack light for easy shinkansen travel!"
        }
    }
}

note_count = 0


async def seed():
    global note_count
    async with httpx.AsyncClient(timeout=60.0) as client:
        print("Logging in...")
        try:
            login_res = await client.post(f"{API_BASE}/auth/login", data={"username": EMAIL, "password": PASSWORD})
            login_res.raise_for_status()
            token = login_res.json()["access_token"]
        except httpx.HTTPStatusError:
            print("User not found, attempting to create...")
            signup_res = await client.post(f"{API_BASE}/auth/signup", json={"email": EMAIL, "password": PASSWORD})
            signup_res.raise_for_status()
            login_res = await client.post(f"{API_BASE}/auth/login", data={"username": EMAIL, "password": PASSWORD})
            token = login_res.json()["access_token"]

        headers = {"Authorization": f"Bearer {token}"}

        async def create_node(title, type_, parent_id=None, content=""):
            res = await client.post(
                f"{API_BASE}/nodes",
                headers=headers,
                json={"title": title, "type": type_, "parent_id": parent_id, "content": content}
            )
            res.raise_for_status()
            return res.json()

        print("Creating folder structure and notes...")
        for root_folder, sub_items in DATA_STRUCTURE.items():
            print(f"\n  Creating root folder: {root_folder}")
            root_node = await create_node(root_folder, "folder")

            for sub_folder, notes in sub_items.items():
                print(f"    Creating sub-folder: {sub_folder}")
                sub_node = await create_node(sub_folder, "folder", root_node["id"])

                for note_title, note_content in notes.items():
                    note_count += 1
                    long_content = f"# {note_title}\n\n" + (note_content + "\n\n") * 5
                    print(f"      [{note_count}] Creating note: {note_title} ({len(long_content)} chars)")
                    await create_node(note_title, "note", sub_node["id"], long_content)

        print(f"\nSeed complete! Created {note_count} notes.")


if __name__ == "__main__":
    asyncio.run(seed())
