"""embedding chunks

Revision ID: 6a5f7c426631
Revises: ef0f657b5149
Create Date: 2026-03-29 18:09:55.760331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a5f7c426631'
down_revision: Union[str, Sequence[str], None] = 'ef0f657b5149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node_embeddings', sa.Column('chunk_index', sa.Integer(), nullable=False))
    op.add_column('node_embeddings', sa.Column('chunk_text', sa.Text(), nullable=False))
    op.add_column('node_embeddings', sa.Column('node_version', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('node_embeddings_node_id_key'), 'node_embeddings', type_='unique')
    op.create_index(op.f('ix_node_embeddings_node_id'), 'node_embeddings', ['node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_embeddings_node_id'), table_name='node_embeddings')
    op.create_unique_constraint(op.f('node_embeddings_node_id_key'), 'node_embeddings', ['node_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('node_embeddings', 'node_version')
    op.drop_column('node_embeddings', 'chunk_text')
    op.drop_column('node_embeddings', 'chunk_index')
    # ### end Alembic commands ###
